name: generadornombres
description: "Generador de Nombres"
publish_to: "none"
version: 1.0.0+1
environment: 
  sdk: ">=2.19.4 <4.0.0"

dependencies: 
  flutter:
    sdk: flutter
  
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

